{{- with .Values.chatui }}
# TODO: In the future this should probably be its own chart
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "llama-stack-chatui.fullname" $ }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "llama-stack-chatui.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "llama-stack-chatui.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with .imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $.Chart.Name }}
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: "{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .service.port }}
              protocol: TCP
          env:
            - name: BASE_URL
              value: http://llama-stack:5001
          livenessProbe:
            {{- tpl (toYaml .livenessProbe) $ | nindent 12 }}
          readinessProbe:
            {{- tpl (toYaml .readinessProbe) $ | nindent 12 }}
          startupProbe:
            {{- tpl (toYaml .startupProbe) $ | nindent 12 }}
          resources:
            {{- toYaml .resources | nindent 12 }}
      {{- with .nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}