FROM registry.access.redhat.com/ubi9/nodejs-22-minimal@sha256:99182cbf8b651399f360d85cd48b7ac5fcfe14d49bbc3d48d9e2d1bc035564d2

WORKDIR /opt/app-root/src

USER root

RUN microdnf install -y python3.12 python3-pip && \
    microdnf clean all

RUN pip3 install uv

RUN chown -R 1001:0 /opt/app-root/src

USER 1001

CMD npx -y supergateway --stdio "uvx --from mcp-salesforce-connector salesforce"


